-- ==========================================
-- SCRIPT 001: KHỞI TẠO HỆ THỐNG SEAL
-- ==========================================

-- 1. Bảng Account
CREATE TABLE Account (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(500) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Role VARCHAR(50) NOT NULL, -- Coordinator / Judge / Mentor / Leader
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    RejectedReason NVARCHAR(500) NULL,
    JudgeType VARCHAR(50) NULL, -- Internal / Guest
    IsDeleted BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

-- 2. Bảng Event
CREATE TABLE Event (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    Status VARCHAR(50) DEFAULT 'Draft',
    IsDeleted BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    UpdatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 3. Bảng Track
CREATE TABLE Track (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EventId INT NOT NULL FOREIGN KEY REFERENCES Event(Id),
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    MaxTeams INT NULL,
    IsDeleted BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    UpdatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 4. Bảng MentorAssign (UNIQUE Constraint chống assign trùng)
CREATE TABLE MentorAssign (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MentorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    TrackId INT NOT NULL FOREIGN KEY REFERENCES Track(Id),
    AssignedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    AssignedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    CONSTRAINT UQ_Mentor_Track UNIQUE (MentorId, TrackId)
);

-- 5. Bảng Prize
CREATE TABLE Prize (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TrackId INT NOT NULL FOREIGN KEY REFERENCES Track(Id),
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    RankPosition INT NOT NULL,
    Amount DECIMAL(18,2) NULL
);

-- 6. Bảng Round
CREATE TABLE Round (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TrackId INT NOT NULL FOREIGN KEY REFERENCES Track(Id),
    Name NVARCHAR(255) NOT NULL,
    OrderIndex INT NOT NULL,
    StartTime DATETIME2 NOT NULL,
    EndTime DATETIME2 NOT NULL,
    AdvancingSlots INT NULL,
    Status VARCHAR(50) DEFAULT 'Upcoming',
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    UpdatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 7. Bảng CriterionTemplate
CREATE TABLE CriterionTemplate (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 8. Bảng CriterionTemplateItem
CREATE TABLE CriterionTemplateItem (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TemplateId INT NOT NULL FOREIGN KEY REFERENCES CriterionTemplate(Id),
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    MaxScore FLOAT NOT NULL,
    Weight FLOAT NOT NULL
);

-- 9. Bảng Topic
CREATE TABLE Topic (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    RoundId INT NOT NULL FOREIGN KEY REFERENCES Round(Id),
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Requirements NVARCHAR(MAX) NULL,
    AttachmentUrl VARCHAR(1000) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    UpdatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 10. Bảng Team (Status 'Draft' để block đội chưa đủ 3-5 người)
CREATE TABLE Team (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TrackId INT NOT NULL FOREIGN KEY REFERENCES Track(Id),
    LeaderId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    MentorId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    TopicId INT NULL FOREIGN KEY REFERENCES Topic(Id),
    TeamName NVARCHAR(255) NOT NULL,
    University NVARCHAR(255) NOT NULL,
    GithubRepoLink VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Draft', 
    IsDeleted BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    UpdatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 11. Bảng TeamMember
CREATE TABLE TeamMember (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TeamId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Team(Id),
    FullName NVARCHAR(255) NOT NULL,
    StudentCode VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(20) NULL,
    IsLeader BIT DEFAULT 0,
    IsFPTStudent BIT DEFAULT 1,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    UpdatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 12. Bảng Submission (UNIQUE chống Double Submit + INDEX tăng tốc query)
CREATE TABLE Submission (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeamId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Team(Id),
    RoundId INT NOT NULL FOREIGN KEY REFERENCES Round(Id),
    DemoUrl VARCHAR(1000) NULL,
    ReportUrl VARCHAR(1000) NULL,
    AiEvaluation NVARCHAR(MAX) NULL,
    IsDisqualified BIT DEFAULT 0,
    DisqualifyReason NVARCHAR(500) NULL,
    DisqualifiedAt DATETIME2 NULL,
    DisqualifiedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Submission_Team_Round UNIQUE (TeamId, RoundId)
);
CREATE NONCLUSTERED INDEX IX_Submission_RoundId ON Submission(RoundId);

-- 13. Bảng JudgeAssign
CREATE TABLE JudgeAssign (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    JudgeId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    RoundId INT NOT NULL FOREIGN KEY REFERENCES Round(Id),
    AssignedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    AssignedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    CONSTRAINT UQ_Judge_Round UNIQUE (JudgeId, RoundId)
);

-- 14. Bảng Criterion
CREATE TABLE Criterion (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    RoundId INT NOT NULL FOREIGN KEY REFERENCES Round(Id),
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    MaxScore FLOAT NOT NULL,
    Weight FLOAT NOT NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id),
    UpdatedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Account(Id)
);

-- 15. Bảng ScoreRecord (UNIQUE tránh 1 giám khảo chấm 1 tiêu chí 2 lần)
CREATE TABLE ScoreRecord (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SubmissionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Submission(Id),
    JudgeId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    CriterionId INT NOT NULL FOREIGN KEY REFERENCES Criterion(Id),
    Score FLOAT NOT NULL,
    Comment NVARCHAR(MAX) NULL,
    IsCalibration BIT DEFAULT 0,
    ScoredAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT UQ_ScoreRecord UNIQUE (SubmissionId, JudgeId, CriterionId)
);
CREATE NONCLUSTERED INDEX IX_ScoreRecord_SubmissionId ON ScoreRecord(SubmissionId);

-- 16. Bảng Ranking
CREATE TABLE Ranking (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeamId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Team(Id),
    RoundId INT NOT NULL FOREIGN KEY REFERENCES Round(Id),
    TotalScore FLOAT NOT NULL,
    RankPosition INT NOT NULL,
    IsAdvancing BIT DEFAULT 0,
    CalculatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Ranking_Team_Round UNIQUE (TeamId, RoundId)
);

-- 17. Bảng Notification
CREATE TABLE Notification (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    AccountId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    Title NVARCHAR(255) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    Type VARCHAR(50) NOT NULL,
    IsRead BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

-- 18. Bảng AuditLog
CREATE TABLE AuditLog (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PerformedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
    Action VARCHAR(100) NOT NULL,
    EntityName VARCHAR(100) NOT NULL,
    EntityId VARCHAR(100) NOT NULL,
    OldValues NVARCHAR(MAX) NULL,
    NewValues NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);