export const judgeProfile = {
  displayName: "Internal Judge",
  role: "Judge",
  type: "Internal Judge",
  activeEvent: "FPT Hackathon 2026",
};

export const currentTime = new Date("2026-05-25T12:00:00+07:00");

export const judgeRounds = [
  {
    id: "round-prototype",
    name: "Prototype Submission",
    status: "Scoring",
    startTime: "2026-05-24T08:00:00+07:00",
    endTime: "2026-05-25T10:00:00+07:00",
    trackName: "Web Application",
    assignedSubmissions: 3,
    completedSubmissions: 1,
    ranking: { calculatedAt: null },
  },
  {
    id: "round-final",
    name: "Final Presentation",
    status: "Upcoming",
    startTime: "2026-05-25T14:00:00+07:00",
    endTime: "2026-05-25T18:00:00+07:00",
    trackName: "AI Solution",
    assignedSubmissions: 2,
    completedSubmissions: 0,
    ranking: { calculatedAt: null },
  },
  {
    id: "round-locked",
    name: "Idea Pitch",
    status: "Closed",
    startTime: "2026-05-23T08:00:00+07:00",
    endTime: "2026-05-23T18:00:00+07:00",
    trackName: "Web Application",
    assignedSubmissions: 2,
    completedSubmissions: 2,
    ranking: { calculatedAt: "2026-05-24T09:00:00+07:00" },
  },
];

export const judgeCriteria = [
  { id: "innovation", name: "Innovation", description: "Novelty and creativity of the proposed solution.", maxScore: 10, weight: 0.3 },
  { id: "technical", name: "Technical Quality", description: "Implementation quality, architecture, and reliability.", maxScore: 10, weight: 0.25 },
  { id: "impact", name: "Impact", description: "Potential value for users and stakeholders.", maxScore: 10, weight: 0.2 },
  { id: "presentation", name: "Presentation", description: "Clarity of demo, report, and explanation.", maxScore: 10, weight: 0.15 },
  { id: "feasibility", name: "Feasibility", description: "Practicality of delivery and adoption.", maxScore: 10, weight: 0.1 },
];

export const judgeSubmissions = [
  {
    id: "sub-nova-prototype",
    roundId: "round-prototype",
    roundName: "Prototype Submission",
    teamName: "Team Nova",
    university: "FPT University HCMC",
    demoUrl: "https://example.com/team-nova-demo",
    reportUrl: "https://example.com/team-nova-report.pdf",
    status: "Not scored",
    submittedAt: "2026-05-25T09:20:00+07:00",
    ranking: { calculatedAt: null },
    scores: {},
    comments: {},
    scoredAt: null,
    totalScore: null,
  },
  {
    id: "sub-catalysts-prototype",
    roundId: "round-prototype",
    roundName: "Prototype Submission",
    teamName: "Code Catalysts",
    university: "FPT University HCMC",
    demoUrl: "https://example.com/code-catalysts-demo",
    reportUrl: "https://example.com/code-catalysts-report.pdf",
    status: "Draft",
    submittedAt: "2026-05-25T09:40:00+07:00",
    ranking: { calculatedAt: null },
    scores: { innovation: 8, technical: 7.5 },
    comments: { innovation: "Clear problem framing." },
    scoredAt: null,
    totalScore: null,
  },
  {
    id: "sub-byte-prototype",
    roundId: "round-prototype",
    roundName: "Prototype Submission",
    teamName: "Byte Builders",
    university: "FPT University Can Tho",
    demoUrl: "https://example.com/byte-builders-demo",
    reportUrl: "https://example.com/byte-builders-report.pdf",
    status: "Scored",
    submittedAt: "2026-05-25T08:55:00+07:00",
    ranking: { calculatedAt: null },
    scores: { innovation: 8.5, technical: 8, impact: 7.5, presentation: 8, feasibility: 7 },
    comments: { impact: "Strong user value with room for clearer rollout." },
    scoredAt: "2026-05-25T11:10:00+07:00",
    totalScore: 7.9,
  },
  {
    id: "sub-final-ai",
    roundId: "round-final",
    roundName: "Final Presentation",
    teamName: "AI Pioneers",
    university: "University of Science",
    demoUrl: "https://example.com/ai-pioneers-demo",
    reportUrl: "https://example.com/ai-pioneers-report.pdf",
    status: "Locked until scoring time",
    submittedAt: "2026-05-25T11:05:00+07:00",
    ranking: { calculatedAt: null },
    scores: {},
    comments: {},
    scoredAt: null,
    totalScore: null,
  },
  {
    id: "sub-locked-pitch",
    roundId: "round-locked",
    roundName: "Idea Pitch",
    teamName: "Syntax Squad",
    university: "University of Science",
    demoUrl: "https://example.com/syntax-squad-demo",
    reportUrl: "https://example.com/syntax-squad-report.pdf",
    status: "Locked",
    submittedAt: "2026-05-23T17:45:00+07:00",
    ranking: { calculatedAt: "2026-05-24T09:00:00+07:00" },
    scores: { innovation: 7, technical: 6.5, impact: 6, presentation: 7, feasibility: 6.5 },
    comments: { presentation: "Well-structured pitch." },
    scoredAt: "2026-05-23T20:10:00+07:00",
    totalScore: 6.6,
  },
];

export const recentScoringActivity = [
  { id: "act-1", teamName: "Byte Builders", action: "Submitted score set", time: "50 minutes ago", tone: "success" },
  { id: "act-2", teamName: "Code Catalysts", action: "Saved draft scores", time: "1 hour ago", tone: "warning" },
  { id: "act-3", teamName: "Team Nova", action: "Opened scoring workspace", time: "Today", tone: "info" },
];
