-- Thêm cột EventId vào bảng Topic
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Topic' AND COLUMN_NAME = 'EventId')
BEGIN
    ALTER TABLE Topic ADD EventId INT NULL;
END
GO

-- Sửa cột RoundId cho phép NULL
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Topic' AND COLUMN_NAME = 'RoundId' AND IS_NULLABLE = 'NO')
BEGIN
    ALTER TABLE Topic ALTER COLUMN RoundId INT NULL;
END
GO

-- Thêm khóa ngoại cho EventId
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_Topic_EventId')
BEGIN
    ALTER TABLE Topic ADD CONSTRAINT FK_Topic_EventId FOREIGN KEY (EventId) REFERENCES [Event](Id);
END
GO
