// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealHackathon.Infrastructure.Data;

#nullable disable

namespace SealHackathon.Infrastructure.Migrations
{
    [DbContext(typeof(SealDbContext))]
    partial class SealDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SealHackathon.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailConfirmToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Leader");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Account__3214EC07700DABC1");

                    b.HasIndex(new[] { "Username" }, "UQ_Account_Username")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Account__A9D105348F2FC7A6")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC07BB7F158C");

                    b.HasIndex("PerformedBy");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Criterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxScore")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Criterio__3214EC077B396BFB");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoundId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Criterion", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.CriterionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Criterio__3214EC07E6E3C59A");

                    b.HasIndex("CreatedBy");

                    b.ToTable("CriterionTemplate", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.CriterionTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxScore")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Criterio__3214EC070FBBE9BE");

                    b.HasIndex("TemplateId");

                    b.ToTable("CriterionTemplateItem", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Event__3214EC079EBC7F8B");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.EventAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JudgeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id")
                        .HasName("PK__EventAcc__3214EC070D900EC6");

                    b.HasIndex("AssignedBy");

                    b.HasIndex(new[] { "AccountId" }, "IX_EventAccount_AccountId");

                    b.HasIndex(new[] { "EventId" }, "IX_EventAccount_EventId");

                    b.HasIndex(new[] { "EventId", "AccountId", "EventRole" }, "UQ_EventAccount")
                        .IsUnique();

                    b.ToTable("EventAccount", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.JudgeAssign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JudgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__JudgeAss__3214EC07FEBFA91D");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoundId");

                    b.HasIndex(new[] { "JudgeId", "RoundId" }, "UQ_Judge_Round")
                        .IsUnique();

                    b.ToTable("JudgeAssign", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.MentorAssign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__MentorAs__3214EC07E5501BF2");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("TrackId");

                    b.HasIndex(new[] { "MentorId", "TrackId" }, "UQ_Mentor_Track")
                        .IsUnique();

                    b.ToTable("MentorAssign", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC075349CFA0");

                    b.HasIndex("AccountId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Prize__3214EC076684359B");

                    b.HasIndex(new[] { "EventId", "RankPosition" }, "UQ_Prize_Event_RankPosition")
                        .IsUnique();

                    b.ToTable("Prize", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Ranking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsAdvancing")
                        .HasColumnType("bit");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalScore")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Ranking__3214EC075BB438CE");

                    b.HasIndex("RoundId");

                    b.HasIndex(new[] { "TeamId", "RoundId" }, "UQ_Ranking_Team_Round")
                        .IsUnique();

                    b.ToTable("Ranking", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvancingSlots")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Upcoming");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Round__3214EC079D798DF5");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TrackId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Round", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.RoundTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id")
                        .HasName("PK_RoundTeam");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("TeamId");

                    b.HasIndex("TopicId");

                    b.HasIndex(new[] { "RoundId", "TeamId" }, "UQ_RoundTeam_Round_Team")
                        .IsUnique();

                    b.ToTable("RoundTeam", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.SchemaVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Applied")
                        .HasColumnType("datetime");

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_SchemaVersions_Id");

                    b.ToTable("SchemaVersions");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.ScoreRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<Guid>("JudgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ScoreRec__3214EC07B3B11CEB");

                    b.HasIndex("CriterionId");

                    b.HasIndex("JudgeId");

                    b.HasIndex(new[] { "SubmissionId" }, "IX_ScoreRecord_SubmissionId");

                    b.HasIndex(new[] { "SubmissionId", "JudgeId", "CriterionId" }, "UQ_ScoreRecord")
                        .IsUnique();

                    b.ToTable("ScoreRecord", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DisqualifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DisqualifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisqualifyReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisqualified")
                        .HasColumnType("bit");

                    b.Property<string>("PresentationUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Submissi__3214EC0768EED89B");

                    b.HasIndex("DisqualifiedBy");

                    b.HasIndex(new[] { "RoundId" }, "IX_Submission_RoundId");

                    b.HasIndex(new[] { "TeamId", "RoundId" }, "UQ_Submission_Team_Round")
                        .IsUnique();

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisqualifyReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GithubRepoLink")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Team__3214EC07A4B7A492");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LeaderId");

                    b.HasIndex("MentorId");

                    b.HasIndex("TopicId");

                    b.HasIndex("TrackId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsFptstudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsFPTStudent");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__TeamMemb__3214EC07B84759AD");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeamId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TeamMember", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakScoreRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<Guid>("JudgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("TieBreakSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_TieBreakScoreRecord");

                    b.HasIndex("CriterionId");

                    b.HasIndex(new[] { "JudgeId" }, "IX_TieBreakScoreRecord_JudgeId");

                    b.HasIndex(new[] { "TieBreakSubmissionId", "JudgeId", "CriterionId" }, "UQ_TieBreakScoreRecord")
                        .IsUnique();

                    b.ToTable("TieBreakScoreRecord", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PendingScoring");

                    b.HasKey("Id")
                        .HasName("PK_TieBreakSession");

                    b.HasIndex(new[] { "RoundId", "RankPosition", "Status" }, "IX_TieBreakSession_Round_Rank_Status");

                    b.HasIndex(new[] { "RoundId", "RankPosition" }, "UQ_TieBreakSession_Open_Round_Rank")
                        .IsUnique()
                        .HasFilter("[Status] = 'PendingScoring'");

                    b.ToTable("TieBreakSession", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TieBreakSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_TieBreakSubmission");

                    b.HasIndex(new[] { "SubmissionId" }, "IX_TieBreakSubmission_SubmissionId");

                    b.HasIndex(new[] { "TieBreakSessionId", "SubmissionId" }, "UQ_TieBreakSubmission_Session_Submission")
                        .IsUnique();

                    b.ToTable("TieBreakSubmission", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoundId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Topic__3214EC075C11D878");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EventId");

                    b.HasIndex("RoundId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTeams")
                        .HasColumnType("int");

                    b.Property<int?>("MinMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Track__3214EC07F9DA9866");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "EventId" }, "UQ_Track_Event_Final")
                        .IsUnique()
                        .HasFilter("[IsFinal] = 1 AND [IsDeleted] = 0");

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "PerformedByNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .IsRequired()
                        .HasConstraintName("FK__AuditLog__Perfor__2645B050");

                    b.Navigation("PerformedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Criterion", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("CriterionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Criterion__Creat__0B91BA14");

                    b.HasOne("SealHackathon.Domain.Entities.Round", "Round")
                        .WithMany("Criteria")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("FK__Criterion__Round__08B54D69");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "UpdatedByNavigation")
                        .WithMany("CriterionUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__Criterion__Updat__0C85DE4D");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Round");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.CriterionTemplate", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("CriterionTemplates")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Criterion__Creat__5812160E");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.CriterionTemplateItem", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.CriterionTemplate", "Template")
                        .WithMany("CriterionTemplateItems")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__Criterion__Templ__5AEE82B9");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Event", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("EventCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Event__CreatedBy__32E0915F");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "UpdatedByNavigation")
                        .WithMany("EventUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__Event__UpdatedBy__33D4B598");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.EventAccount", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "Account")
                        .WithMany("EventAccountAccounts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__EventAcco__Accou__38996AB5");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "AssignedByNavigation")
                        .WithMany("EventAccountAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK__EventAcco__Assig__3A81B327");

                    b.HasOne("SealHackathon.Domain.Entities.Event", "Event")
                        .WithMany("EventAccounts")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__EventAcco__Event__37A5467C");

                    b.Navigation("Account");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.JudgeAssign", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "AssignedByNavigation")
                        .WithMany("JudgeAssignAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("FK__JudgeAssi__Assig__05D8E0BE");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "Judge")
                        .WithMany("JudgeAssignJudges")
                        .HasForeignKey("JudgeId")
                        .IsRequired()
                        .HasConstraintName("FK__JudgeAssi__Judge__02FC7413");

                    b.HasOne("SealHackathon.Domain.Entities.Round", "Round")
                        .WithMany("JudgeAssigns")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("FK__JudgeAssi__Round__03F0984C");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Judge");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.MentorAssign", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "AssignedByNavigation")
                        .WithMany("MentorAssignAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("FK__MentorAss__Assig__49C3F6B7");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "Mentor")
                        .WithMany("MentorAssignMentors")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorAss__Mento__46E78A0C");

                    b.HasOne("SealHackathon.Domain.Entities.Track", "Track")
                        .WithMany("MentorAssigns")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorAss__Track__47DBAE45");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__Accou__208CD6FA");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Prize", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Event", "Event")
                        .WithMany("Prizes")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_Prize_Event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Ranking", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Round", "Round")
                        .WithMany("Rankings")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__RoundId__1AD3FDA4");

                    b.HasOne("SealHackathon.Domain.Entities.Team", "Team")
                        .WithMany("Rankings")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__TeamId__19DFD96B");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Round", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("RoundCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Round__CreatedBy__534D60F1");

                    b.HasOne("SealHackathon.Domain.Entities.Track", "Track")
                        .WithMany("Rounds")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Round__TrackId__4F7CD00D");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "UpdatedByNavigation")
                        .WithMany("RoundUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__Round__UpdatedBy__5441852A");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Track");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.RoundTeam", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "AssignedByNavigation")
                        .WithMany("RoundTeamAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK_RoundTeam_AssignedBy");

                    b.HasOne("SealHackathon.Domain.Entities.Round", "Round")
                        .WithMany("RoundTeams")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("FK_RoundTeam_Round");

                    b.HasOne("SealHackathon.Domain.Entities.Team", "Team")
                        .WithMany("RoundTeams")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK_RoundTeam_Team");

                    b.HasOne("SealHackathon.Domain.Entities.Topic", "Topic")
                        .WithMany("RoundTeams")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK_RoundTeam_Topic");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Round");

                    b.Navigation("Team");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.ScoreRecord", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Criterion", "Criterion")
                        .WithMany("ScoreRecords")
                        .HasForeignKey("CriterionId")
                        .IsRequired()
                        .HasConstraintName("FK__ScoreReco__Crite__1332DBDC");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "Judge")
                        .WithMany("ScoreRecords")
                        .HasForeignKey("JudgeId")
                        .IsRequired()
                        .HasConstraintName("FK__ScoreReco__Judge__123EB7A3");

                    b.HasOne("SealHackathon.Domain.Entities.Submission", "Submission")
                        .WithMany("ScoreRecords")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK__ScoreReco__Submi__114A936A");

                    b.Navigation("Criterion");

                    b.Navigation("Judge");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Submission", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "DisqualifiedByNavigation")
                        .WithMany("Submissions")
                        .HasForeignKey("DisqualifiedBy")
                        .HasConstraintName("FK__Submissio__Disqu__7E37BEF6");

                    b.HasOne("SealHackathon.Domain.Entities.Round", "Round")
                        .WithMany("Submissions")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__Round__7C4F7684");

                    b.HasOne("SealHackathon.Domain.Entities.Team", "Team")
                        .WithMany("Submissions")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__TeamI__7B5B524B");

                    b.Navigation("DisqualifiedByNavigation");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Team", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("TeamCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Team__CreatedBy__6D0D32F4");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "Leader")
                        .WithMany("TeamLeaders")
                        .HasForeignKey("LeaderId")
                        .IsRequired()
                        .HasConstraintName("FK__Team__LeaderId__66603565");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "Mentor")
                        .WithMany("TeamMentors")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK__Team__MentorId__6754599E");

                    b.HasOne("SealHackathon.Domain.Entities.Topic", "Topic")
                        .WithMany("Teams")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK__Team__TopicId__68487DD7");

                    b.HasOne("SealHackathon.Domain.Entities.Track", "Track")
                        .WithMany("Teams")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Team__TrackId__656C112C");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "UpdatedByNavigation")
                        .WithMany("TeamUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__Team__UpdatedBy__6E01572D");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Leader");

                    b.Navigation("Mentor");

                    b.Navigation("Topic");

                    b.Navigation("Track");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("TeamMemberCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__TeamMembe__Creat__75A278F5");

                    b.HasOne("SealHackathon.Domain.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK__TeamMembe__TeamI__70DDC3D8");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "UpdatedByNavigation")
                        .WithMany("TeamMemberUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__TeamMembe__Updat__76969D2E");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Team");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakScoreRecord", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .IsRequired()
                        .HasConstraintName("FK_TieBreakScoreRecord_Criterion");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId")
                        .IsRequired()
                        .HasConstraintName("FK_TieBreakScoreRecord_Judge");

                    b.HasOne("SealHackathon.Domain.Entities.TieBreakSubmission", "TieBreakSubmission")
                        .WithMany("TieBreakScoreRecords")
                        .HasForeignKey("TieBreakSubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK_TieBreakScoreRecord_TieBreakSubmission");

                    b.Navigation("Criterion");

                    b.Navigation("Judge");

                    b.Navigation("TieBreakSubmission");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakSession", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("FK_TieBreakSession_Round");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakSubmission", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK_TieBreakSubmission_Submission");

                    b.HasOne("SealHackathon.Domain.Entities.TieBreakSession", "TieBreakSession")
                        .WithMany("TieBreakSubmissions")
                        .HasForeignKey("TieBreakSessionId")
                        .IsRequired()
                        .HasConstraintName("FK_TieBreakSubmission_TieBreakSession");

                    b.Navigation("Submission");

                    b.Navigation("TieBreakSession");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Topic", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("TopicCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Topic__CreatedBy__60A75C0F");

                    b.HasOne("SealHackathon.Domain.Entities.Event", "Event")
                        .WithMany("Topics")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_Topic_EventId");

                    b.HasOne("SealHackathon.Domain.Entities.Round", "Round")
                        .WithMany("Topics")
                        .HasForeignKey("RoundId")
                        .HasConstraintName("FK__Topic__RoundId__5DCAEF64");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "UpdatedByNavigation")
                        .WithMany("TopicUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__Topic__UpdatedBy__619B8048");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Event");

                    b.Navigation("Round");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Track", b =>
                {
                    b.HasOne("SealHackathon.Domain.Entities.Account", "CreatedByNavigation")
                        .WithMany("TrackCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Track__CreatedBy__4222D4EF");

                    b.HasOne("SealHackathon.Domain.Entities.Event", "Event")
                        .WithMany("Tracks")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__Track__EventId__3E52440B");

                    b.HasOne("SealHackathon.Domain.Entities.Account", "UpdatedByNavigation")
                        .WithMany("TrackUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__Track__UpdatedBy__4316F928");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Event");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Account", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CriterionCreatedByNavigations");

                    b.Navigation("CriterionTemplates");

                    b.Navigation("CriterionUpdatedByNavigations");

                    b.Navigation("EventAccountAccounts");

                    b.Navigation("EventAccountAssignedByNavigations");

                    b.Navigation("EventCreatedByNavigations");

                    b.Navigation("EventUpdatedByNavigations");

                    b.Navigation("JudgeAssignAssignedByNavigations");

                    b.Navigation("JudgeAssignJudges");

                    b.Navigation("MentorAssignAssignedByNavigations");

                    b.Navigation("MentorAssignMentors");

                    b.Navigation("Notifications");

                    b.Navigation("RoundCreatedByNavigations");

                    b.Navigation("RoundTeamAssignedByNavigations");

                    b.Navigation("RoundUpdatedByNavigations");

                    b.Navigation("ScoreRecords");

                    b.Navigation("Submissions");

                    b.Navigation("TeamCreatedByNavigations");

                    b.Navigation("TeamLeaders");

                    b.Navigation("TeamMemberCreatedByNavigations");

                    b.Navigation("TeamMemberUpdatedByNavigations");

                    b.Navigation("TeamMentors");

                    b.Navigation("TeamUpdatedByNavigations");

                    b.Navigation("TopicCreatedByNavigations");

                    b.Navigation("TopicUpdatedByNavigations");

                    b.Navigation("TrackCreatedByNavigations");

                    b.Navigation("TrackUpdatedByNavigations");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Criterion", b =>
                {
                    b.Navigation("ScoreRecords");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.CriterionTemplate", b =>
                {
                    b.Navigation("CriterionTemplateItems");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventAccounts");

                    b.Navigation("Prizes");

                    b.Navigation("Topics");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Round", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("JudgeAssigns");

                    b.Navigation("Rankings");

                    b.Navigation("RoundTeams");

                    b.Navigation("Submissions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Submission", b =>
                {
                    b.Navigation("ScoreRecords");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Team", b =>
                {
                    b.Navigation("Rankings");

                    b.Navigation("RoundTeams");

                    b.Navigation("Submissions");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakSession", b =>
                {
                    b.Navigation("TieBreakSubmissions");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.TieBreakSubmission", b =>
                {
                    b.Navigation("TieBreakScoreRecords");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Topic", b =>
                {
                    b.Navigation("RoundTeams");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SealHackathon.Domain.Entities.Track", b =>
                {
                    b.Navigation("MentorAssigns");

                    b.Navigation("Rounds");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
