export const dashboardStats = [
  {
    id: "teams",
    label: "Total registered teams",
    value: "128",
    tone: "orange",
    delta: "+12 this week",
    helper: "92 approved",
  },
  {
    id: "pending",
    label: "Pending teams",
    value: "18",
    tone: "amber",
    delta: "Needs review",
    helper: "6 incomplete",
  },
  {
    id: "round",
    label: "Current active round",
    value: "Round 2",
    tone: "blue",
    delta: "36h left",
    helper: "Final build",
  },
  {
    id: "unscored",
    label: "Unscored submissions",
    value: "24",
    tone: "red",
    delta: "Judges alerted",
    helper: "76% scored",
  },
];

export const recentActivity = [
  {
    id: "a1",
    user: "Coordinator Admin",
    action: "opened Round 2 submissions",
    time: "12 minutes ago",
    tone: "info",
  },
  {
    id: "a2",
    user: "Mentor Linh Tran",
    action: "accepted 2 team assignments",
    time: "34 minutes ago",
    tone: "success",
  },
  {
    id: "a3",
    user: "Judge Minh Pham",
    action: "submitted scores for Team Nova",
    time: "1 hour ago",
    tone: "orange",
  },
  {
    id: "a4",
    user: "System",
    action: "flagged Team Pixel for missing repository",
    time: "2 hours ago",
    tone: "warning",
  },
];

export const events = [
  {
    id: "ev1",
    name: "FPT Hackathon 2026",
    description: "University-wide software engineering competition",
    startDate: "2026-05-20",
    endDate: "2026-05-27",
    status: "Ongoing",
    active: true,
    teams: 128,
  },
  {
    id: "ev2",
    name: "SEAL Innovation Sprint",
    description: "Prototype sprint for product validation",
    startDate: "2026-07-04",
    endDate: "2026-07-06",
    status: "Draft",
    active: false,
    teams: 0,
  },
  {
    id: "ev3",
    name: "AI for Education Challenge",
    description: "Applied AI challenge for learning tools",
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    status: "Closed",
    active: false,
    teams: 54,
  },
];

export const tracks = [
  {
    id: "tr1",
    name: "Web App",
    event: "FPT Hackathon 2026",
    maxTeams: 50,
    teams: 42,
    mentors: 8,
    topics: 6,
    status: "Open",
  },
  {
    id: "tr2",
    name: "Mobile App",
    event: "FPT Hackathon 2026",
    maxTeams: 40,
    teams: 33,
    mentors: 6,
    topics: 5,
    status: "Open",
  },
  {
    id: "tr3",
    name: "AI Solution",
    event: "FPT Hackathon 2026",
    maxTeams: 35,
    teams: 31,
    mentors: 7,
    topics: 4,
    status: "Full",
  },
  {
    id: "tr4",
    name: "Game & Simulation",
    event: "FPT Hackathon 2026",
    maxTeams: 25,
    teams: 22,
    mentors: 4,
    topics: 3,
    status: "Open",
  },
];

export const rounds = [
  {
    id: "r1",
    name: "Registration",
    startTime: "May 20, 08:00",
    endTime: "May 21, 17:00",
    status: "Closed",
    advancingSlots: 128,
    progress: 100,
  },
  {
    id: "r2",
    name: "Idea Pitch",
    startTime: "May 22, 09:00",
    endTime: "May 22, 18:00",
    status: "Closed",
    advancingSlots: 96,
    progress: 100,
  },
  {
    id: "r3",
    name: "Development Sprint",
    startTime: "May 23, 08:00",
    endTime: "May 25, 20:00",
    status: "Active",
    advancingSlots: 64,
    progress: 68,
  },
  {
    id: "r4",
    name: "Final Scoring",
    startTime: "May 26, 09:00",
    endTime: "May 26, 18:00",
    status: "Scoring",
    advancingSlots: 12,
    progress: 22,
  },
  {
    id: "r5",
    name: "Awards",
    startTime: "May 27, 09:00",
    endTime: "May 27, 12:00",
    status: "Upcoming",
    advancingSlots: 3,
    progress: 0,
  },
];

export const criteria = [
  { id: "c1", name: "Innovation", maxScore: 10, weight: 0.3, status: "Active" },
  {
    id: "c2",
    name: "Technical Quality",
    maxScore: 10,
    weight: 0.25,
    status: "Active",
  },
  { id: "c3", name: "Impact", maxScore: 10, weight: 0.2, status: "Active" },
  {
    id: "c4",
    name: "Presentation",
    maxScore: 10,
    weight: 0.15,
    status: "Active",
  },
  {
    id: "c5",
    name: "Feasibility",
    maxScore: 10,
    weight: 0.1,
    status: "Active",
  },
];

export const topics = [
  {
    id: "tp1",
    name: "Smart Campus Assistant",
    track: "Web App",
    round: "Development Sprint",
    attachments: 3,
    assignedTeams: 18,
    randomAssigned: true,
    status: "Published",
  },
  {
    id: "tp2",
    name: "Mental Health Companion",
    track: "Mobile App",
    round: "Development Sprint",
    attachments: 2,
    assignedTeams: 14,
    randomAssigned: true,
    status: "Published",
  },
  {
    id: "tp3",
    name: "AI Code Review Coach",
    track: "AI Solution",
    round: "Final Scoring",
    attachments: 4,
    assignedTeams: 11,
    randomAssigned: false,
    status: "Draft",
  },
];

export const users = [
  {
    id: "u1",
    name: "An Nguyen",
    email: "an.nguyen@fpt.edu.vn",
    role: "Leader",
    team: "Team Nova",
    status: "Pending",
    submittedAt: "May 24, 09:18",
  },
  {
    id: "u2",
    name: "Bao Tran",
    email: "bao.tran@fpt.edu.vn",
    role: "Leader",
    team: "Byte Builders",
    status: "Pending",
    submittedAt: "May 24, 10:02",
  },
  {
    id: "u3",
    name: "Chi Le",
    email: "chi.le@fpt.edu.vn",
    role: "Leader",
    team: "UX Warriors",
    status: "Approved",
    submittedAt: "May 23, 16:45",
  },
  {
    id: "u4",
    name: "Duc Pham",
    email: "duc.pham@fpt.edu.vn",
    role: "Leader",
    team: "Cloud Nine",
    status: "Rejected",
    submittedAt: "May 23, 13:24",
  },
];

export const teams = [
  {
    id: "tm1",
    name: "Team Nova",
    leader: "An Nguyen",
    members: 5,
    track: "Web App",
    mentor: "Linh Tran",
    status: "Pending",
    submission: "Uploaded",
    score: 86,
    readiness: 84,
  },
  {
    id: "tm2",
    name: "Byte Builders",
    leader: "Bao Tran",
    members: 4,
    track: "AI Solution",
    mentor: "Unassigned",
    status: "Pending",
    submission: "Missing demo",
    score: 0,
    readiness: 52,
  },
  {
    id: "tm3",
    name: "UX Warriors",
    leader: "Chi Le",
    members: 5,
    track: "Mobile App",
    mentor: "Huy Vo",
    status: "Approved",
    submission: "Uploaded",
    score: 91,
    readiness: 96,
  },
  {
    id: "tm4",
    name: "Cloud Nine",
    leader: "Duc Pham",
    members: 3,
    track: "Web App",
    mentor: "Mai Do",
    status: "Disqualified",
    submission: "Late",
    score: 0,
    readiness: 20,
  },
];

export const mentors = [
  {
    id: "m1",
    name: "Linh Tran",
    expertise: "React, UX",
    tracks: ["Web App"],
    teams: 3,
    workload: 100,
    status: "At limit",
  },
  {
    id: "m2",
    name: "Huy Vo",
    expertise: "Flutter, Firebase",
    tracks: ["Mobile App"],
    teams: 2,
    workload: 67,
    status: "Available",
  },
  {
    id: "m3",
    name: "Mai Do",
    expertise: "Cloud, DevOps",
    tracks: ["Web App", "AI Solution"],
    teams: 4,
    workload: 80,
    status: "Busy",
  },
];

export const judges = [
  {
    id: "j1",
    name: "Dr. Thanh Ho",
    type: "Internal",
    rounds: ["Final Scoring"],
    status: "Active",
    assignedTeams: 16,
    completedScores: 12,
  },
  {
    id: "j2",
    name: "Ms. Ha Nguyen",
    type: "Guest",
    rounds: ["Idea Pitch", "Final Scoring"],
    status: "Invited",
    assignedTeams: 12,
    completedScores: 4,
  },
  {
    id: "j3",
    name: "Mr. Khoa Bui",
    type: "Internal",
    rounds: ["Development Sprint"],
    status: "Active",
    assignedTeams: 10,
    completedScores: 10,
  },
];

export const results = [
  {
    id: "rs1",
    rank: 1,
    team: "UX Warriors",
    track: "Mobile App",
    finalScore: 91.4,
    innovation: 9.3,
    technical: 9.1,
    impact: 9.2,
    status: "Advancing",
  },
  {
    id: "rs2",
    rank: 2,
    team: "Team Nova",
    track: "Web App",
    finalScore: 86.2,
    innovation: 8.8,
    technical: 8.4,
    impact: 8.7,
    status: "Advancing",
  },
  {
    id: "rs3",
    rank: 3,
    team: "Data Sparks",
    track: "AI Solution",
    finalScore: 84.7,
    innovation: 8.9,
    technical: 8.2,
    impact: 8.1,
    status: "Waiting",
  },
  {
    id: "rs4",
    rank: 4,
    team: "Pixel Labs",
    track: "Game & Simulation",
    finalScore: 81.5,
    innovation: 8.2,
    technical: 8.0,
    impact: 8.3,
    status: "Waiting",
  },
];

export const exportHistory = [
  {
    id: "ex1",
    file: "teams-final-round.csv",
    type: "CSV",
    createdBy: "Coordinator Admin",
    createdAt: "May 24, 11:20",
    status: "Ready",
  },
  {
    id: "ex2",
    file: "anonymous-rbl-data.xlsx",
    type: "Excel",
    createdBy: "Coordinator Admin",
    createdAt: "May 24, 10:40",
    status: "Processing",
  },
  {
    id: "ex3",
    file: "audit-log-may.csv",
    type: "CSV",
    createdBy: "System",
    createdAt: "May 23, 18:00",
    status: "Ready",
  },
];

export const auditLogs = [
  {
    id: "lg1",
    user: "Coordinator Admin",
    action: "Updated criteria weight",
    entity: "Criteria",
    timestamp: "May 24, 11:32",
    severity: "warning",
    oldValues: "Technical: 0.20",
    newValues: "Technical: 0.25",
  },
  {
    id: "lg2",
    user: "Coordinator Admin",
    action: "Approved team",
    entity: "Team Nova",
    timestamp: "May 24, 10:57",
    severity: "info",
    oldValues: "Pending",
    newValues: "Approved",
  },
  {
    id: "lg3",
    user: "System",
    action: "Export generated",
    entity: "Export",
    timestamp: "May 24, 10:40",
    severity: "info",
    oldValues: "Queued",
    newValues: "Processing",
  },
  {
    id: "lg4",
    user: "Coordinator Admin",
    action: "Disqualified team",
    entity: "Cloud Nine",
    timestamp: "May 23, 19:12",
    severity: "critical",
    oldValues: "Approved",
    newValues: "Disqualified: late submission",
  },
];
